name: "Create Namespace"
description: "Create a namespace in Okteto Cloud"
inputs:
  namespace: 
    description: "The name of the namespace"
    required: true
  members: 
    description: "Comma-separated list of users that will have access to the namespace in Okteto; you can use either their Okteto username or their email."
    required: false
  log-level:
    description: "Log level string. Valid options are debug, info, warn, error"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.namespace }}
    - ${{ inputs.members }}
    - ${{ inputs.log-level }}
branding:
  color: 'green'
  icon: 'grid'